# Build the manager binary
FROM reg.docker.alibaba-inc.com/golang-quality/go-coverage:1.19-20221223111023 as builder
ARG TARGETOS
ARG TARGETARCH

WORKDIR /workspace
# Copy the go source
COPY . /workspace

# Build
# the GOARCH has not a default value to allow the binary be built according to the host where the command
# was called. For example, if we call make docker-build in a local env which has the Apple Silicon M1 SO
# the docker BUILDPLATFORM arg will be linux/arm64 when for Apple x86 it will be linux/amd64. Therefore,
# by leaving it empty we can ensure that the container and binary shipped on it will have the same platform.
RUN CGO_ENABLED=0 GOOS=${TARGETOS:-linux} GOARCH=${TARGETARCH:-amd64} go build -a -o manager main.go

# Use distroless as minimal base image to package the manager binary
# Refer to https://github.com/GoogleContainerTools/distroless for more details
FROM reg.docker.alibaba-inc.com/golang-quality/go-coverage:1.19-20221223111023

RUN go env -w GOPROXY="https://goproxy.cn,https://mirrors.aliyun.com/goproxy,direct" GOPRIVATE="gitlab.alipay-inc.com,gitlab.alibaba-inc.com,code.alipay.com"
# RUN yum install -y curl iputils bind-utils

WORKDIR /
COPY --from=builder /workspace/manager .
USER 65532:65532

ENTRYPOINT ["/manager"]
