apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: controller-manager-mutating
webhooks:
  - name: mutating-pod.apps.kusionstack.io
    sideEffects: NoneOnDryRun
    admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      service:
        namespace: kusionstack-system
        name: controller-manager
        path: /mutating-generic
    failurePolicy: Fail
    rules:
      - apiGroups:
          - "*"
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - pods
          - pods/status
        scope: '*'
    objectSelector:
      matchExpressions:
        - key: kusionstack.io/control
          operator: In
          values:
            - 'true'
  - name: mutating-generic.apps.kusionstack.io
    sideEffects: NoneOnDryRun
    admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      service:
        namespace: kusionstack-system
        name: controller-manager
        path: /mutating-generic
    failurePolicy: Fail
    rules:
      - apiGroups:
          - "apps.kusionstack.io"
        apiVersions:
          - "*"
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - "*/*"
        scope: '*'
---

apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: controller-manager-validating
webhooks:
  - name: validating-pod.apps.kusionstack.io
    sideEffects: NoneOnDryRun
    admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      service:
        namespace: kusionstack-system
        name: controller-manager
        path: /validating-generic
    failurePolicy: Fail
    rules:
      - apiGroups:
          - "*"
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - pods
        scope: '*'
    objectSelector:
      matchExpressions:
        - key: kusionstack.io/control
          operator: In
          values:
            - 'true'
  - name: validating-generic.apps.kusionstack.io
    sideEffects: NoneOnDryRun
    admissionReviewVersions: ["v1", "v1beta1"]
    clientConfig:
      service:
        namespace: kusionstack-system
        name: controller-manager
        path: /validating-generic
    failurePolicy: Fail
    rules:
      - apiGroups:
          - "apps.kusionstack.io"
        apiVersions:
          - "*"
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - "*/*"
        scope: '*'