apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    {{- toYaml .Values.commonLabels | nindent 4 }}
    control-plane: {{ .Values.controlPlane }}
  name: kusionstack-operating
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ if .Values.sharding.enabled }}{{ .Values.sharding.replicas }}{{ else }}{{ .Values.managerReplicas }}{{ end }}
  selector:
    matchLabels:
      control-plane: {{ .Values.controlPlane }}
  serviceName: {{ .Values.webhookServiceName }}
  template:
    metadata:
      labels:
        control-plane: {{ .Values.controlPlane }}
        {{- if .Values.sharding.enabled }}
        ctrlmesh.kusionstack.io/enable-proxy: 'true'
        {{- end}}
    spec:
      containers:
      - args:
        - --leader-elect=true
        - --cert-dir=/webhook-certs
        - --dns-name={{ .Values.webhookServiceName }}.{{ .Values.namespace }}.svc
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - -v=4
        command:
        - /manager
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      terminationGracePeriodSeconds: 0
      volumes:
      - name: webhook-certs
        secret:
          secretName: webhook-certs
{{- if .Values.sharding.enabled }}
  updateStrategy:
    type: OnDelete
{{- end }}