---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: kusionstack-controller-manager-mutating
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      namespace: {{ .Values.namespace }}
      name: {{ .Values.webhookServiceName }}
      path: /mutating-generic
  failurePolicy: Fail
  name: mutating-pod.apps.kusionstack.io
  objectSelector:
    matchExpressions:
    - key: kusionstack.io/control
      operator: In
      values:
      - "true"
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - pods
    - pods/status
    scope: '*'
  sideEffects: None
- name: mutating-generic.apps.kusionstack.io
  sideEffects: None
  admissionReviewVersions: 
  - v1
  - v1beta1
  clientConfig:
    service:
      namespace: {{ .Values.namespace }}
      name: {{ .Values.webhookServiceName }}
      path: /mutating-generic
  failurePolicy: Fail
  rules:
  - apiGroups:
    - "apps.kusionstack.io"
    apiVersions:
    - "*"
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - "*/*"
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: kusionstack-controller-manager-validating
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      namespace: {{ .Values.namespace }}
      name: {{ .Values.webhookServiceName }}
      path: /validating-generic
  failurePolicy: Fail
  name: validating-pod.apps.kusionstack.io
  objectSelector:
    matchExpressions:
    - key: kusionstack.io/control
      operator: In
      values:
      - "true"
  rules:
  - apiGroups:
    - '*'
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - pods
    scope: '*'
  sideEffects: None
- name: validating-generic.apps.kusionstack.io
  sideEffects: None
  admissionReviewVersions: 
  - v1
  - v1beta1
  clientConfig:
    service:
      namespace: {{ .Values.namespace }}
      name: {{ .Values.webhookServiceName }}
      path: /validating-generic
  failurePolicy: Fail
  rules:
  - apiGroups:
    - "apps.kusionstack.io"
    apiVersions:
    - "*"
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - "*/*"
    scope: '*'
- name: validating-pvc.apps.kusionstack.io
  sideEffects: None
  admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      namespace: {{ .Values.namespace }}
      name: {{ .Values.webhookServiceName }}
      path: /validating-generic
  failurePolicy: Fail
  rules:
    - apiGroups:
        - "*"
      apiVersions:
        - v1
      operations:
        - DELETE
      resources:
        - persistentvolumeclaims
      scope: '*'
  objectSelector:
    matchExpressions:
      - key: kusionstack.io/control
        operator: In
        values:
          - 'true'