---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - controllerrevisions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.kusionstack.io
  resources:
  - collasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.kusionstack.io
  resources:
  - collasets/finalizers
  verbs:
  - update
- apiGroups:
  - apps.kusionstack.io
  resources:
  - collasets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps.kusionstack.io
  resources:
  - resourcecontexts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.kusionstack.io
  resources:
  - resourcecontexts/finalizers
  verbs:
  - update
- apiGroups:
  - apps.kusionstack.io
  resources:
  - resourcecontexts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps.kusionstack.io
  resources:
  - rulesets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.kusionstack.io
  resources:
  - rulesets/finalizers
  verbs:
  - update
- apiGroups:
  - apps.kusionstack.io
  resources:
  - rulesets/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/status
  verbs:
  - get
  - patch
  - update
